Repository openbouffalo/buildroot_bouffalo, pull requests merged in 2023-02, with the labels that each got.

#22 Bump Kernel to 6.2.0-rc7
  boot/oblfr/oblfr.mk
  configs/pine64_ox64_defconfig
  configs/pine64_ox64_full_defconfig
Labels: enhancement

#25 Fix link for mergebin in Kconfig files
  package/riscv-unknown-elf-gcc/Config.in.host
Labels: documentation

#27 Update Buildroot to 2022.11.1 Version
  .github/workflows/buildroot.yml
Labels: enhancement

#28 Bump Kernel to 6.2-rc8
  configs/pine64_ox64_defconfig
  configs/pine64_ox64_full_defconfig
Labels: enhancement

#29 Publish SDK and include setup script for SDK
  .github/workflows/buildroot.yml
  configs/pine64_ox64_defconfig
  configs/pine64_ox64_full_defconfig
Labels: enhancement

#31 add gpio and TRNG drivers
  .github/workflows/buildroot.yml
  README.md
  board/pine64/ox64/linux_defconfig
  board/pine64/ox64/mergebin.py
  board/pine64/ox64/patches/linux/0019-add-timer-node-to-dts-file.patch
  board/pine64/ox64/patches/linux/0024-riscv-dts-bflb-m1s-Fix-address-size-cells.patch
  board/pine64/ox64/patches/linux/0025-riscv-dts-bflb-ox64-Fix-address-size-cells.patch
  board/pine64/ox64/patches/linux/0026-Add-timer-node-for-OpenSBI-1.2-compatibility.patch
  board/pine64/ox64/patches/linux/0027-Tabstops-are-8-chars-not-4.patch
  board/pine64/ox64/patches/linux/0028-Add-GPIO-PINCTRL-and-HWRNG-Crypto-drivers.patch
  board/pine64/ox64/patches/linux/0029-Update-device-trees-for-new-GPIO-and-HWRNG-drivers.patch
  board/pine64/ox64/patches/linux/0031-Bring-M1s-device-tree-up-to-date-with-Ox64-s-changes.patch
  board/pine64/ox64/post-build.sh
  configs/pine64_ox64_defconfig
  configs/pine64_ox64_full_defconfig
Labels: enhancement

#35 Fix TRNG Build
  board/pine64/ox64/linux_defconfig
Labels: bug

#36 Bump Kernel Version to 6.2
  configs/pine64_ox64_defconfig
  configs/pine64_ox64_full_defconfig
Labels: enhancement
