Repository openbouffalo/buildroot_bouffalo, pull requests merged in 2023-01, with the labels that each got.

#3 Kernel Updates for SDHCI and UART2 + Buildroot Updates
  .github/workflows/buildroot.yml
  board/pine64/ox64/bl808-pine64-ox64.dtb
  board/pine64/ox64/bl808-pine64-ox64.dts
  board/pine64/ox64/linux_defconfig
  board/pine64/ox64/patches/linux/0013-disable-card-detection-dma-cap-clock-quirks.patch
  board/pine64/ox64/patches/linux/0014-UART2-working-under-Linux.patch
  board/pine64/ox64/patches/linux/0015-dts-bl808-add-fake-sdh-clock-at-96MHz.patch
  board/pine64/ox64/patches/linux/0016-sdhci-bflb-enable-additional-quirks.patch
  board/pine64/ox64/patches/linux/0017-Disable-flash-rootfs-for-now-edit-bootargs-to-use-SD.patch
  configs/pine64_ox64_defconfig
  configs/pine64_ox64_full_defconfig
Labels: enhancement

#8 Buildroot now builds OpenSBI
  .github/workflows/buildroot.yml
  .gitignore
  board/pine64/ox64/patches/linux/0018-rename-dts-files.patch
  board/pine64/ox64/patches/linux/0019-add-timer-node-to-dts-file.patch
  board/pine64/ox64/patches/opensbi/0001-lib-utils-serial-Add-Bouffalo-Lab-serial-driver.patch
  board/pine64/ox64/patches/opensbi/0002-update-opensbi-firmware-base-image-and-dtb-addresses.patch
  configs/pine64_ox64_defconfig
  configs/pine64_ox64_full_defconfig
Labels: enhancement

#9 Update Mergebin.py
  package/mergebin/mergebin.py
Labels: bug

#11 Integrate low_load building into buildroot
  .github/workflows/buildroot.yml
  Config.in
  board/pine64/ox64/mergebin.py
  board/pine64/ox64/post-build.sh
  boot/Config.in
  boot/oblfr/Config.in
  boot/oblfr/oblfr.mk
  configs/pine64_ox64_defconfig
  configs/pine64_ox64_full_defconfig
  external.mk
  package/Config.in
  package/Config.in.host
  package/blmcusdk/Config.in.host
  package/blmcusdk/blmcusdk.mk
  package/mergebin/Readme.md
  package/riscv-unknown-elf-gcc/Config.in.host
  package/riscv-unknown-elf-gcc/riscv-unknown-elf-gcc.mk
Labels: enhancement

#13 Kernel 6.2 rc5
  board/pine64/ox64/linux_defconfig
  board/pine64/ox64/patches/linux/0017-Disable-flash-rootfs-for-now-edit-bootargs-to-use-SD.patch
  board/pine64/ox64/patches/linux/0020-tty-serial-bflb_uart-fix-leaked-ISR-registration.patch
  board/pine64/ox64/patches/linux/0021-mmc-sdhci-bflb-remove-unnecessary-quirks.patch
  configs/pine64_ox64_defconfig
  configs/pine64_ox64_full_defconfig
Labels: enhancement

#14 Include pins for programming and console UART in README
  README.md
Labels: documentation

#18 Update to Kernel 6.2-rc6
  configs/pine64_ox64_defconfig
  configs/pine64_ox64_full_defconfig
Labels: enhancement
